theme: jekyll-theme-minimal
title: Shuchu Han
description: 
myavatar: "/images/shuchu_hp.png"
email: "shuchu.han@gmail.com"
address: "4 Independence Way Suite 200,Princeton, NJ 08540"
phone: "(609)-951-2489"
